version: "3.9"
services:
  app:
    build:
      context: ./app
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules
    environment:
      - PORT=3000
      - API_SCHEMA=http
      - API_HOST=localhost
      - API_PORT=8000
    networks:
      - shared
    depends_on:
      - api

  api:
    build:
      context: ./api
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
      - api_node_modules:/api/node_modules
    environment:
      - PORT=8000
      - DB_HOST=mysql
      - DB_PORT=8001
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_DATABASE=quick-copy-paste
    networks:
      - shared
    depends_on:
      - mysql

  mysql:
    image: mysql:8-debian
    ports:
      - "8001:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=quick-copy-paste
    networks:
      - shared

volumes:
  mysql_volume:
  api_node_modules:
  app_node_modules:


networks:
  shared:
    external: true
